### ISSUE TITLE
Tests are currently failing

### ISSUE THREAD

**Issue by oubiwann** [clojusc/coati#1]
We need to get these puppies passing ...

**Comment by bjorstrom** [comment]
Looks like either of these two would address this:
- getting the lint stuff set up
- removing lint checks from the Travis CI test

**Comment by bjorstrom** [comment]
So, this is still a problem ... but for a different reason:

The updated deps included a new version of Twig: with the fix provided above, the tests passed with Twig 0.2.3 but not with 0.2.4. The reason is that the latest Twig uses libraries that need the latest sl4j ... I think updating Twig per the instructions at  http://www.slf4j.org/codes.html (section "java.lang.NoClassDefFoundError: org/slf4j/event/LoggingEvent") should do the trick.

See issue https://github.com/clojusc/twig/issues/2 for more details. Once that is addressed, using the next version of Twig (presumably 0.2.5) should fix this ...

**Comment by bjorstrom** [comment]
Okay, Twig 0.2.5 has been published ...

**Comment by bjorstrom** [comment]
Okay, with several more updates to Twig and the Coati `project.clj` file, it seems we've licked this one: tests are now passing on master.

Closing ...
